### PR TITLE
V2.0.0

### PR DESCRIPTION
**Pull request by dangreenisrael**
# V2.0.0 release

##  Breaking changes:
- We now only support node versions `^10.12.0 || >=12.0.0` which is [inline with eslint 7.](https://eslint.org/docs/user-guide/migrating-to-7.0.0#node-js-8-is-no-longer-supported)
- We drop all deprecated rules.

## To do:

- [x] Fix linting for ts
- [x] - Drop deprecated rules
- [x] - Update README

### CODE REVIEW

**Comment by dangreenisrael** [comment]
I opened https://github.com/dangreenisrael/eslint-plugin-jest-formatting/pull/92 by accident as it was meant to be a draft

**Comment by dangreenisrael** [comment]
As usual, there is context in commit messages

**Comment by dangreenisrael** [comment]
cc @MichaelDeBoey

**Comment by MichaelDeBoey** [comment]
Really nice @dangreenisrael! 🎉

Hope to see it soon on NPM and in the release notes 😉

**Pull request merged**
