### PR TITLE
Remove docs for deleted `padding-before-*` rules

### PR DESCRIPTION
**Pull request by bmish**
It looks like these rules were renamed/deprecated/removed already.

### CODE REVIEW

**Comment by hockeybuggy** [comment]
Ah yep. These were removed in version `2.0.0`: https://github.com/dangreenisrael/eslint-plugin-jest-formatting/commit/05f2dfb81549a193f1ac80395550f5869a744d82

Good catch @bmish

**Review by hockeybuggy — APPROVED** [review]
:thumbsup: Looks good to me :sparkles:

**Comment by bmish** [comment]
Shall we merge this? @twelve17 @dangreenisrael

**Comment by benkimpel** [comment]
@bmish You've been tagging `twelve17`, but I'm not sure that they have merge privileges on this repo (although they have contributed). I'll merge this one. Thanks for the PR.

**Pull request merged**
